name: Test on PR

on:
    pull_request:
        branches:
            - Challenge_8

jobs:
    build:
        runs-on: ubuntu-latest
        environment: DB
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
            - name: create env file
              run: |
                  touch .env.test
                  echo DB=${{ secrets.DB }} >> .env.test
                  echo DB_HOST=${{ secrets.DB_HOST }} >> .env.test
                  echo DB_USER=${{ secrets.DB_USER }} >> .env.test
                  echo DB_PASS=${{ secrets.DB_PASS }} >> .env.test
                  echo DB_PORT=${{ secrets.DB_PORT }} >> .env.test
                  echo CLOUD_NAME=${{ secrets.CLOUD_NAME }} >> .env.test
                  echo CLOUD_API_KEY=${{ secrets.CLOUD_API_KEY }} >> .env.test
                  echo CLOUD_API_SECRET=${{ secrets.CLOUD_API_SECRET }} >> .env.test
                  echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.test
                  echo SESSION_EXPIRE=${{ secrets.SESSION_EXPIRE }} >> .env.test
            - run: npm ci
            - run: npm run lint
            - run: npm test
            - run: npm run build --if-present
